import wd, time
from wd import click, dlg, CLEAN, setv, key, focus_map
s = wd.session(); R = wd.Rec(s, 's17')
s.js(CLEAN); wd.st(s)
C = "return [waypoints.length, tracks.length, routes.length, (typeof osrmRoutes!=='undefined'?osrmRoutes.length:null), waypoints.filter(m=>map.hasLayer(m)).length, tracks.filter(t=>t.polyline&&map.hasLayer(t.polyline)).length]"
s.js("map.setView([43.19, 44.84], 12, {animate:false})"); time.sleep(1)
R('👁 скрыть всё', lambda: click(s, '#btn-toggle-work-objects'), extra=C + ".concat([document.getElementById('btn-toggle-work-objects').title])")
R('👁 показать всё', lambda: click(s, '#btn-toggle-work-objects'), extra=C + ".concat([document.getElementById('btn-toggle-work-objects').title])")
R('🗑 очистить → окно', lambda: click(s, '#toolbar button[title="Очистить рабочие данные с карты"]'), extra="return [document.getElementById('modal-clear-confirm').classList.contains('open'), document.getElementById('clear-confirm-info').innerText.replace(/\\s+/g,' ').slice(0,200), document.getElementById('clear-data-list').innerText.replace(/\\s+/g,' ').slice(0,300), document.getElementById('clear-delete-btn').innerText, document.getElementById('clear-delete-btn').disabled]")
R('Снять', lambda: click(s, '#modal-clear-confirm button[onclick="setClearDataSelection(false)"]'), extra="return [document.querySelectorAll('#clear-data-list input:checked').length, document.getElementById('clear-delete-btn').innerText, document.getElementById('clear-delete-btn').disabled]")
R('Все', lambda: click(s, '#modal-clear-confirm button[onclick="setClearDataSelection(true)"]'), extra="return [document.querySelectorAll('#clear-data-list input:checked').length, document.getElementById('clear-delete-btn').innerText]")
R('👁 Скрыть всё (из окна)', lambda: click(s, '#modal-clear-confirm button[onclick*="hideAllWorkObjects"]'), extra=C)
R('показать обратно', lambda: click(s, '#btn-toggle-work-objects'), extra=C, shot=False)
R('Отмена', lambda: (click(s, '#toolbar button[title="Очистить рабочие данные с карты"]'), click(s, '#modal-clear-confirm .btn-row .btn-secondary:not([onclick*=hide]), #modal-clear-confirm button[onclick="closeModal(\'modal-clear-confirm\')"]')), extra="return document.getElementById('modal-clear-confirm').classList.contains('open')")
R('быстро: только OSRM', lambda: (click(s, '#toolbar button[title="Очистить рабочие данные с карты"]'), click(s, '#clear-quick-osrm')), wait=1, extra=C + ".concat([document.getElementById('modal-dialog').classList.contains('open'), document.getElementById('modal-dialog-message').innerText.slice(0,100)])")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('  confirm', lambda: dlg(s), extra=C)
R('Ctrl+Z после очистки', lambda: (s.js(CLEAN), focus_map(s), key(s, 'z', ('ctrl',))), extra=C)
R('удалить выбранное: только треки', lambda: (click(s, '#toolbar button[title="Очистить рабочие данные с карты"]'), click(s, '#modal-clear-confirm button[onclick="setClearDataSelection(false)"]'), s.js("const i=[...document.querySelectorAll('#clear-data-list input')].find(i=>/трек/i.test(i.closest('label,div').innerText)); if(i){i.click()}"), click(s, '#clear-delete-btn')), wait=1, extra=C + ".concat([document.getElementById('modal-dialog').classList.contains('open'), document.getElementById('modal-dialog-message').innerText.slice(0,100)])")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('  confirm', lambda: dlg(s), extra=C)
R('Ctrl+Z вернуть треки', lambda: (s.js(CLEAN), focus_map(s), key(s, 'z', ('ctrl',))), extra=C)
s.js(CLEAN)
# О программе
R('О программе', lambda: click(s, '#toolbar button[title="О программе"]'), wait=1.5, extra="return [document.getElementById('about-version').textContent, document.getElementById('about-platform').textContent, document.getElementById('about-license').innerText.replace(/\\s+/g,' ').slice(0,200), document.getElementById('modal-about').innerText.replace(/\\s+/g,' ').slice(0,600)]")
R('Проверить обновления', lambda: click(s, '#btn-check-update'), wait=4, extra="return [document.getElementById('update-status').textContent, document.getElementById('btn-check-update').textContent]")
R('about links', None, extra="return [...document.querySelectorAll('#modal-about a, #modal-about [onclick]')].map(e=>(e.innerText||'').trim().slice(0,30)+' :: '+(e.getAttribute('href')||e.getAttribute('onclick')||'').slice(0,60))", shot=False)
s.js(CLEAN)
# линейка
R('линейка: 3 точки', lambda: (focus_map(s), key(s, 'm'), wd.xclick(s, 500, 500), wd.xclick(s, 700, 500), wd.xclick(s, 700, 650)), extra="return document.getElementById('ruler-panel').innerText.replace(/\\s+/g,' ')")
R('линейка: ↩', lambda: click(s, '#ruler-panel [onclick="undoRulerPoint()"]'), extra="return document.getElementById('ruler-panel').innerText.replace(/\\s+/g,' ')")
R('линейка: 〜 В трек', lambda: click(s, '#ruler-track-btn'), extra="return [tracks.length, tracks[tracks.length-1].name, tracks[tracks.length-1].points.length, currentMode]")
R('линейка: Очистить', lambda: (focus_map(s), key(s, 'm'), wd.xclick(s, 500, 500), wd.xclick(s, 600, 500), click(s, '#ruler-panel [onclick="clearRuler()"]')), extra="return document.getElementById('ruler-panel').innerText.replace(/\\s+/g,' ')")
R('линейка: ✕', lambda: click(s, '#ruler-panel [onclick="setMode(\'hand\')"]'), extra="return [currentMode, getComputedStyle(document.getElementById('ruler-panel')).display]")
# карта: зум, Z, Обзор, виджеты
R('+', lambda: click(s, '.leaflet-control-zoom-in'), wait=1, extra="return map.getZoom()")
R('−', lambda: click(s, '.leaflet-control-zoom-out'), wait=1, extra="return map.getZoom()")
R('кнопка Z (уровень)', lambda: click(s, '.leaflet-control a[title*="масштаб"], .leaflet-control .tn-zoom-level, .leaflet-bar a.tn-zoom'), wait=1, extra="return [map.getZoom(), [...document.querySelectorAll('.leaflet-control-container a, .leaflet-control-container button')].map(a=>(a.title||a.textContent).trim().slice(0,40))]")
R('Обзор (на карте)', lambda: (focus_map(s), key(s, 'w'), click(s, 'a[title^="Обзор (H)"]')), extra="return [currentMode, document.getElementById('sb-mode').textContent]")
R('колёсико мыши (реальное)', lambda: (wd.xdo('mousemove', '800', '450'), wd.xdo('click', '4')), wait=1.2, extra="return map.getZoom()")
R('перетаскивание карты (реальное)', lambda: (lambda c: (wd.xdo('mousemove', '800', '450'), wd.xdo('mousedown', '1'), wd.xdo('mousemove', '850', '480'), wd.xdo('mousemove', '900', '500'), wd.xdo('mouseup', '1')))(0), wait=1, extra="return [map.getCenter().lat.toFixed(4), map.getCenter().lng.toFixed(4)]")
R('виджеты: скрыть', lambda: click(s, '.tn-widgets-toggle, button[title="Скрыть виджеты"]'), extra="return [document.querySelector('.tn-widgets')?.hidden, localStorage.getItem('tnd-widgets-hidden')]")
R('виджеты: показать', lambda: click(s, '.tn-widgets-toggle, button[title="Показать виджеты"]'), extra="return [document.querySelector('.tn-widgets')?.hidden, localStorage.getItem('tnd-widgets-hidden')]")
R('статусбар', None, extra="return document.getElementById('statusbar')?.innerText.replace(/\\s+/g,' ')", shot=False)
R.save()
