import wd, time
from wd import click, dlg, typein, CLEAN
s = wd.session(); R = wd.Rec(s, 's5')
s.js(CLEAN); wd.st(s)
open_w = lambda: (s.js(CLEAN), click(s, '#toolbar button[title="Список точек"]'))
R('open list', open_w, extra="return [document.getElementById('wpt-set-select').options.length, [...document.getElementById('wpt-set-select').options].map(o=>o.text), document.querySelectorAll('#wpt-tbody tr').length]")
R('set select change', lambda: s.js("const sel=document.getElementById('wpt-set-select'); sel.selectedIndex=0; sel.dispatchEvent(new Event('change'))"), extra="return [activeSetId, document.querySelectorAll('#wpt-tbody tr').length]")
R('new set +', lambda: (click(s, '#modal-wpts button[title="Новый набор"]'), dlg(s, 'Аудит набор')), extra="return [...document.getElementById('wpt-set-select').options].map(o=>o.text)")
R('select set audit-all', lambda: s.js("const sel=document.getElementById('wpt-set-select'); const i=[...sel.options].findIndex(o=>o.text.startsWith('audit-all')); sel.selectedIndex=i; sel.dispatchEvent(new Event('change'))"), extra="return [activeSetId, document.querySelectorAll('#wpt-tbody tr').length]")
R('hide set 👁', lambda: click(s, '#modal-wpts button[title="Скрыть/показать"]'), extra="return waypointSets.map(x=>[x.name, x.visible]).concat([waypoints.filter(m=>map.hasLayer(m)).length])")
R('show set 👁', lambda: click(s, '#modal-wpts button[title="Скрыть/показать"]'), extra="return waypointSets.map(x=>[x.name, x.visible]).concat([waypoints.filter(m=>map.hasLayer(m)).length])")
R('rename set ✏', lambda: (click(s, '#modal-wpts button[title="Переименовать"]'), dlg(s, 'GPX-набор')), extra="return waypointSets.map(x=>x.name)")
R('search WP0', lambda: typein(s, '#wpt-search', 'WP03'), extra="return [...document.querySelectorAll('#wpt-tbody tr')].map(r=>r.innerText.replace(/\\s+/g,' ').slice(0,40))")
R('search clear', lambda: s.js("const i=document.getElementById('wpt-search'); i.value=''; i.dispatchEvent(new Event('input'))"), extra="return document.querySelectorAll('#wpt-tbody tr').length")
R('row click pans', lambda: (s.js("map.setView([55.75,37.6],10)"), click(s, '#wpt-tbody tr:nth-child(2) td.wpt-name')), extra="return [map.getCenter().lat.toFixed(3), map.getCenter().lng.toFixed(3)]")
R('row map btn yandex', lambda: click(s, '#wpt-tbody tr:nth-child(1) button.wpt-map-btn'), wait=2, extra="return null")
R('select all', lambda: click(s, '#wpt-select-all'), extra="return document.querySelectorAll('#wpt-tbody input.wpt-cb:checked').length")
R('bulk edit open', lambda: click(s, '#modal-wpts button[onclick="toggleBulkEditPanel()"]'), extra="return getComputedStyle(document.getElementById('bulk-edit-panel')).display")
R('bulk apply radius 77 + icon', lambda: (typein(s, '#bulk-radius', '77'), s.js("const b=document.getElementById('bulk-icon'); b.value='★'; b.dispatchEvent(new Event('change'))"), click(s, '#bulk-edit-panel .btn-primary')), extra="return getActiveSet().waypoints.map(m=>[m.wpData.radius, m.wpData.symbol||m.wpData.icon])")
R('bulk color apply', lambda: (click(s, '#wpt-select-all'), click(s, '#wpt-select-all'), click(s, '#modal-wpts button[onclick="toggleBulkEditPanel()"]'), s.js("document.getElementById('bulk-color').value='#00ff00'"), click(s, '#bulk-color-apply'), click(s, '#bulk-edit-panel .btn-primary')), extra="return getActiveSet().waypoints.map(m=>m.wpData.color)")
R('bulk cancel', lambda: (click(s, '#modal-wpts button[onclick="toggleBulkEditPanel()"]'), click(s, '#bulk-edit-panel .btn-secondary')), extra="return getComputedStyle(document.getElementById('bulk-edit-panel')).display")
R('delete selected (1)', lambda: (s.js("document.querySelectorAll('#wpt-tbody input.wpt-cb').forEach(c=>c.checked=false)"), click(s, '#wpt-tbody tr:nth-child(6) input.wpt-cb'), click(s, '#modal-wpts button[onclick="deleteSelectedWaypoints()"]')), wait=0.5, extra="return [document.getElementById('modal-dialog').classList.contains('open'), document.getElementById('modal-dialog-message').innerText]")
R('delete selected confirm', lambda: dlg(s), extra="return [waypoints.length, getActiveSet().waypoints.length]")
R('row ctx (right click)', lambda: wd.rclick_el(s, '#wpt-tbody tr:nth-child(1) td.wpt-name'), extra="return [...document.querySelectorAll('#ctx-menu .ctx-item')].filter(e=>e.offsetParent).map(e=>e.innerText.trim())")
R('ctx props', lambda: click(s, '#ctx-menu [onclick="ctxAction(\'props\')"]'), extra="return [document.getElementById('prop-name').value, document.getElementById('prop-desc').value, document.getElementById('prop-radius').value, document.getElementById('prop-lat').value, document.getElementById('prop-lng').value]")
R('props ext Яндекс', lambda: click(s, '#modal-wpt-props .external-map-btn'), wait=2.5, extra="return null")
R('props edit+save', lambda: (typein(s, '#prop-name', 'WP01-аудит'), typein(s, '#prop-desc', 'Описание аудит'), typein(s, '#prop-radius', '123'), click(s, '#modal-wpt-props .icon-cell[data-symbol="★"]'), typein(s, '#prop-lat', '43.171'), click(s, '#modal-wpt-props .btn-primary')), extra="const d=waypoints.find(m=>m.wpData.name.startsWith('WP01-'))?.wpData; return d && [d.name, d.desc, d.radius, d.symbol||d.icon, d.lat]")
R('props name 17 chars', lambda: (wd.rclick_el(s, '#wpt-tbody tr:nth-child(1) td.wpt-name'), click(s, '#ctx-menu [onclick="ctxAction(\'props\')"]'), typein(s, '#prop-name', 'ABCDEFGHIJKLMNOPQRS')), extra="return document.getElementById('prop-name').value")
R('props cancel', lambda: click(s, '#modal-wpt-props .btn-secondary'), extra="return waypoints.some(m=>m.wpData.name==='ABCDEFGHIJKLMNOP')")
R('footer save .gpx (dup)', lambda: (s.js("window.__audit.dialogQueue.push(arguments[0])", wd.A+'/home/Документы/TrophyNavigatorTest/audit-export/wplist.gpx'), click(s, '#modal-wpts .save-btn[onclick="saveWaypointsGPX()"]')), wait=2)
R('footer load .wpt (dup)', lambda: (s.js("window.__audit.dialogQueue.push(arguments[0])", wd.A+'/home/Загрузки/audit-ozi.wpt'), click(s, '#modal-wpts .open-btn[onclick*="loadWPT"]')), wait=2, extra="return [waypoints.length, waypointSets.map(x=>x.name)]")
R('delete set ✕', lambda: (click(s, '#toolbar button[title="Список точек"]'), click(s, '#modal-wpts button[title="Удалить набор"]')), wait=0.5, extra="return [document.getElementById('modal-dialog-message').innerText, activeSetId]")
R('delete set confirm', lambda: dlg(s), extra="return [waypoints.length, waypointSets.map(x=>x.name)]")
R('clear all 🗑', lambda: click(s, '#modal-wpts button[onclick="clearAllWaypoints()"]'), wait=0.5, extra="return document.getElementById('modal-dialog-message').innerText")
R('clear all cancel', lambda: dlg(s, ok=False), extra="return waypoints.length")
R('close ✕', lambda: click(s, '#modal-wpts .modal-close'))
R.save()
