import wd, time
from wd import click, dlg, CLEAN, setv, key, focus_map
s = wd.session(); R = wd.Rec(s, 's6')
s.js(CLEAN); s.js('try{ if(currentTrackDraw) cancelTrackDraw(); }catch(e){}'); wd.st(s)
EXP = wd.WORK + '/audit-export/'
openw = lambda: wd.open_by(s, '#toolbar button[title="Список треков"]', 'modal-tracks')
T = "const t=tracks.find(x=>x.id===selectedTrackId); return t ? [t.id, t.name, t.color, t.width, t.points.length, t.visible, t.points[0].lat.toFixed(4), t.pointSize] : [selectedTrackId, __tnTest.stats().tracks]"
R('open list', openw, extra="return [...document.querySelectorAll('#track-list .track-item')].map(e=>e.innerText.replace(/\\s+/g,' ').slice(0,60))")
R('select track (row click)', lambda: click(s, '#track-list .track-item:nth-child(2) .track-meta'), extra=T)
R('rename inline', lambda: setv(s, '#track-list .track-item:nth-child(2) input.track-name', 'Трек-аудит'), extra="return tracks.map(t=>t.name)")
R('color preview', lambda: setv(s, '#track-color-input', '#ff00ff'), extra=T)
R('width 6', lambda: setv(s, '#track-width-input', '6'), extra="return [document.getElementById('track-width-val').textContent]")
R('points 0', lambda: setv(s, '#track-point-size-input', '0'), extra="return [document.getElementById('track-point-size-val').textContent]")
R('save props', lambda: (setv(s, '#track-name-input', 'Трек-свойства'), click(s, '#track-controls .btn-primary')), extra=T)
R('center', lambda: (s.js("__tnTest.setView({center:{lat:55.7,lng:37.6},zoom:5})"), click(s, '#track-controls button[onclick="centerSelectedTrack()"]')), wait=1.2, extra="return [__tnTest.getView().center.lat.toFixed(2), __tnTest.getView().zoom]")
R('reverse', lambda: click(s, '#track-controls button[onclick="reverseSelectedTrack()"]'), extra=T)
R('reverse back', lambda: click(s, '#track-controls button[onclick="reverseSelectedTrack()"]'), extra=T)
R('hide row 👁', lambda: click(s, '#track-list .track-item:nth-child(2) button[title="Скрыть/показать"]'), extra="return tracks.map(t=>[t.name,t.visible])")
R('show row 👁', lambda: click(s, '#track-list .track-item:nth-child(2) button[title="Скрыть/показать"]'), extra="return tracks.map(t=>[t.name,t.visible])")
R('edit start', lambda: (openw(), click(s, '#track-list .track-item:nth-child(2) .track-meta'), click(s, '#track-controls button[onclick="startTrackEdit()"]')), extra="return [currentMode, !!currentTrackEdit, getComputedStyle(document.getElementById('track-build-panel')).display, document.getElementById('track-build-title').innerText]")
R('edit: Esc cancel', lambda: (focus_map(s), key(s, '')), extra="return [currentMode, !!currentTrackEdit]")
R('continue', lambda: (openw(), click(s, '#track-list .track-item:nth-child(2) .track-meta'), click(s, '#track-controls button[onclick="continueSelectedTrack()"]')), extra="return [currentMode, !!currentTrackDraw, document.getElementById('track-build-title').innerText]")
R('continue: add 2 pts (real clicks)', lambda: (wd.xclick(s, 900, 400), wd.xclick(s, 950, 450)), extra="return [currentTrackDraw && currentTrackDraw.points.length, document.getElementById('track-build-count').textContent]")
R('build undo', lambda: click(s, '#track-build-undo-btn'), extra="return [currentTrackDraw && currentTrackDraw.points.length]")
R('build cancel', lambda: click(s, '#track-build-cancel-btn'), extra="return [currentMode, tracks.map(t=>t.points.length)]")
# новый трек
R('new track + (modal)', lambda: (openw(), click(s, '#modal-tracks .btn-primary[onclick="startNewTrack()"]')), extra="return [currentMode, !!currentTrackDraw]")
R('draw 4 pts', lambda: [wd.xclick(s, 500 + i*80, 600 - i*40) for i in range(4)], extra="return [currentTrackDraw && currentTrackDraw.points.length, document.getElementById('track-build-count').textContent, document.getElementById('track-build-len').textContent]")
R('open list while drawing', lambda: click(s, '#toolbar button[title="Список треков"]'), extra="return [document.getElementById('modal-tracks').classList.contains('open'), getComputedStyle(document.getElementById('track-build-panel')).display]")
R('build color/width', lambda: (setv(s, '#track-build-color', '#0000ff'), setv(s, '#track-build-width', '5')), extra="return [currentTrackDraw && currentTrackDraw.color, currentTrackDraw && currentTrackDraw.width, document.getElementById('track-build-width-val').textContent]")
R('build delete point (no selection)', lambda: click(s, '#track-build-delete-point-btn'), extra="return [currentTrackDraw && currentTrackDraw.points.length]")
R('build split (no selection)', lambda: click(s, '#track-build-split-point-btn'), extra="return [currentTrackDraw && currentTrackDraw.points.length]")
R('build finish ✓', lambda: click(s, '#track-build-finish-btn'), extra="return [currentMode, __tnTest.stats().tracks, tracks.at(-1).name, tracks.at(-1).points.length, tracks.at(-1).color]")
R('draw via dblclick finish', lambda: (s.js(CLEAN), key(s, 't'), [wd.xclick(s, 500 + i*60, 300, wait=0.4) for i in range(3)], wd.xclick(s, 700, 300, double=True, wait=1)), extra="return [currentMode, __tnTest.stats().tracks, tracks.at(-1).points.length]")
# плеер
R('player: start w/o selection', lambda: (openw(), click(s, '#track-player-panel .btn-primary')), extra="return [typeof trackPlayer!=='undefined' ? !!trackPlayer : null]")
R('player: check + start', lambda: (click(s, '#track-list .track-item:nth-child(2) input.track-play-cb'), click(s, '#track-player-panel .btn-primary')), wait=2, extra="return Object.keys(window).filter(k=>/player/i.test(k)).slice(0,5)")
R('player: speed 20', lambda: setv(s, '#track-speed', '20'), wait=2, extra="return document.getElementById('track-speed-val').textContent")
R('player: pause', lambda: click(s, '#track-player-panel button[onclick="pauseTrackPlayer()"]'))
R('player: stop', lambda: click(s, '#track-player-panel button[onclick="stopTrackPlayer()"]'))
R('footer save .plt', lambda: (s.js("window.__audit.dialogQueue.push(arguments[0])", EXP + 'trk-footer.plt'), click(s, '#modal-tracks .save-btn[onclick="saveTracksPLT()"]')), wait=2)
R('footer load .gpx (tracks only)', lambda: (s.js("window.__audit.dialogQueue.push(arguments[0])", wd.A + '/home/Загрузки/audit-all.gpx'), click(s, '#modal-tracks .open-btn[onclick*="loadGPXTracks"]')), wait=2, extra="return [__tnTest.stats().wp, __tnTest.stats().tracks, __tnTest.stats().routes]")
R('row delete 🗑', lambda: (openw(), click(s, '#track-list .track-item:last-child button[title="Удалить трек"]')), wait=0.6, extra="return [__tnTest.stats().tracks, document.getElementById('modal-dialog').classList.contains('open'), document.getElementById('modal-dialog-message').innerText]")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('row delete confirm', lambda: dlg(s), extra="return __tnTest.stats().tracks")
R('props delete 🗑', lambda: (openw(), click(s, '#track-list .track-item:last-child .track-meta'), click(s, '#track-controls button[onclick="deleteSelectedTrack()"]')), wait=0.6, extra="return [__tnTest.stats().tracks, document.getElementById('modal-dialog').classList.contains('open')]")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('props delete confirm', lambda: dlg(s), extra="return __tnTest.stats().tracks")
R('Race Report btn', lambda: (openw(), click(s, '#modal-tracks button[onclick="rrOpenDialog()"]')), extra="return [...document.querySelectorAll('.modal-overlay.open')].map(e=>e.id)")
s.js(CLEAN)
R.save()
