import wd, time
from wd import click, dlg, CLEAN, setv, key, focus_map
s = wd.session(); R = wd.Rec(s, 's7')
s.js(CLEAN); s.js('try{ if(currentRouteDraw) cancelRouteDraw(); }catch(e){}'); wd.st(s)
EXP = wd.WORK + '/audit-export/'
openw = lambda: wd.open_by(s, '#toolbar button[title="Список маршрутов по WP"]', 'modal-routes')
RT = "const r=routes.find(x=>x.id===selectedRouteId); return r ? [r.id, r.name, r.color, r.width, r.dashArray, r.points.length, r.labels, r.visible, r.pointRadii] : [selectedRouteId, __tnTest.stats().routes]"
R('open list', openw, extra="return [...document.querySelectorAll('#route-list .route-item')].map(e=>e.innerText.replace(/\\s+/g,' ').slice(0,80))")
R('header click (select+expand)', lambda: click(s, '#route-list .route-item:nth-child(2) .route-meta'), extra=RT + ".concat([getComputedStyle(document.getElementById('route-controls')).display, document.querySelectorAll('#route-list .route-item:nth-child(2) .route-kp').length])")
R('KP rename', lambda: setv(s, '#route-list .route-item:nth-child(2) .route-kp:nth-child(2) input[type=text], #route-list .route-item:nth-child(2) .route-kp:nth-child(2) input:not([type=number])', 'WP01-R'), extra=RT)
R('KP radius', lambda: setv(s, '#route-list .route-item:nth-child(2) .route-kp:nth-child(2) input[type=number]', '444'), extra=RT + ".concat([__tnTest.entities().wp.filter(w=>w.name.startsWith('WP01')).map(w=>[w.name,w.radius])])")
R('KP down ↓', lambda: click(s, '#route-list .route-item:nth-child(2) .route-kp:nth-child(1) .route-kp-btn[title="Ниже"]'), extra=RT)
R('KP up ↑', lambda: click(s, '#route-list .route-item:nth-child(2) .route-kp:nth-child(2) .route-kp-btn[title="Выше"]'), extra=RT)
R('KP delete ✕', lambda: click(s, '#route-list .route-item:nth-child(2) .route-kp:last-child .route-kp-btn.danger'), wait=0.8, extra=RT + ".concat([document.getElementById('modal-dialog').classList.contains('open')])")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('KP delete confirm', lambda: dlg(s), extra=RT)
R('props: name/color/width/dash + save', lambda: (setv(s, '#route-name-input', 'Маршрут-аудит'), setv(s, '#route-color-input', '#00aaff'), setv(s, '#route-width-input', '5'), s.js("const d=document.getElementById('route-dash-input'); d.selectedIndex=Math.min(1,d.options.length-1); d.dispatchEvent(new Event('change'))"), click(s, '#route-controls .btn-primary')), extra=RT + ".concat([[...document.getElementById('route-dash-input').options].map(o=>o.text)])")
R('props center', lambda: (s.js("__tnTest.setView({center:{lat:55.7,lng:37.6},zoom:5})"), click(s, '#route-controls button[onclick="centerSelectedRoute()"]')), wait=1.2, extra="return [__tnTest.getView().center.lat.toFixed(2), __tnTest.getView().zoom]")
R('props hide', lambda: click(s, '#route-controls button[onclick="toggleSelectedRouteVisible()"]'), extra=RT)
R('props show', lambda: click(s, '#route-controls button[onclick="toggleSelectedRouteVisible()"]'), extra=RT)
R('row eye', lambda: click(s, '#route-list .route-item:nth-child(1) .row-act[title="Скрыть/показать"]'), extra="return __tnTest.entities().route.map(r=>[r.name, r.visible])")
R('row eye back', lambda: click(s, '#route-list .route-item:nth-child(1) .row-act[title="Скрыть/показать"]'), extra="return __tnTest.entities().route.map(r=>[r.name, r.visible])")
R('row center', lambda: (s.js("__tnTest.setView({center:{lat:55.7,lng:37.6},zoom:5})"), click(s, '#route-list .route-item:nth-child(1) .row-act[title="Центрировать"]')), wait=1.2, extra="return [__tnTest.getView().center.lat.toFixed(2), __tnTest.getView().zoom]")
R('✎ КП (edit) start', lambda: (openw(), click(s, '#route-list .route-item:nth-child(2) .route-meta'), click(s, '#route-controls button[onclick="startRouteEdit()"]')), extra="return [currentMode, !!currentRouteDraw, getComputedStyle(document.getElementById('route-build-panel')).display, document.getElementById('route-build-title').innerText]")
R('edit: click map adds KP', lambda: wd.xclick(s, 800, 300), extra="return [currentMode, currentRouteDraw && currentRouteDraw.points.length, currentRouteDraw && currentRouteDraw.labels]")
R('edit: Esc', lambda: (focus_map(s), key(s, '')), extra="return [currentMode, !!currentRouteDraw]" + "; ")
# новый маршрут по точкам
def new_route():
    openw(); click(s, '#modal-routes > .modal > .modal-body > .btn-primary, #modal-routes .btn-primary[onclick="startNewRoute()"]')
R('+ Новый маршрут', new_route, extra="return [currentMode, !!currentRouteDraw]")
def click_wps():
    s.js("__tnh.fit(__tnTest.entities().wp.slice(0,5), 0.3)"); time.sleep(1.5)
    for i in range(3):
        p = s.js("return __tnh.xy(__tnh.wp(arguments[0]))", i)
        wd.xclick(s, p[0], p[1], wait=0.5)
R('click 3 WPs', click_wps, extra="return [currentRouteDraw && currentRouteDraw.points.length, currentRouteDraw && currentRouteDraw.labels]")
R('click empty map in route mode', lambda: wd.xclick(s, 300, 800), extra="return [currentRouteDraw && currentRouteDraw.points.length]")
R('open list while building', lambda: click(s, '#toolbar button[title="Список маршрутов по WP"]'), extra="return [document.getElementById('modal-routes').classList.contains('open'), getComputedStyle(document.getElementById('route-build-panel')).display, document.getElementById('route-build-count').textContent, document.getElementById('route-build-dist').textContent, document.getElementById('route-build-kp-list').innerText.slice(0,200)]")
R('build name/style', lambda: (setv(s, '#route-build-name', 'Новый по WP'), setv(s, '#route-build-color', '#ff8800'), setv(s, '#route-build-width', '6')), extra="return [currentRouteDraw.name, currentRouteDraw.color, currentRouteDraw.width]")
R('build ✓ Сохранить', lambda: click(s, '#route-build-panel .btn-primary'), extra="const r=routes.at(-1); return [currentMode, __tnTest.stats().routes, r.name, r.points.length, r.labels, r.pointWaypointIds]")
R('build via R + Отмена', lambda: (s.js(CLEAN), focus_map(s), key(s, 'r'), click_wps(), click(s, '#toolbar button[title="Список маршрутов по WP"]'), click(s, '#route-build-panel .btn-danger')), extra="return [currentMode, __tnTest.stats().routes]")
R('footer save .rte', lambda: (openw(), s.js("window.__audit.dialogQueue.push(arguments[0])", EXP + 'rte-footer.rte'), click(s, '#modal-routes .save-btn[onclick="saveRoutesRTE()"]')), wait=2)
R('footer load .gpx (routes only)', lambda: (openw(), s.js("window.__audit.dialogQueue.push(arguments[0])", wd.A + '/home/Загрузки/audit-route.gpx'), click(s, '#modal-routes .open-btn[onclick*="loadGPXRoutes"]')), wait=2, extra="return [__tnTest.stats().wp, __tnTest.stats().tracks, __tnTest.stats().routes]")
R('row delete', lambda: (openw(), click(s, '#route-list .route-item:last-child .row-act.danger')), wait=0.6, extra="return [__tnTest.stats().routes, document.getElementById('modal-dialog').classList.contains('open')]")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('row delete confirm', lambda: dlg(s), extra="return __tnTest.stats().routes")
R('props delete', lambda: (openw(), click(s, '#route-list .route-item:last-child .route-meta'), click(s, '#route-controls .btn-danger')), wait=0.6, extra="return [__tnTest.stats().routes, document.getElementById('modal-dialog').classList.contains('open')]")
if s.js("return document.getElementById('modal-dialog').classList.contains('open')"): R('props delete confirm', lambda: dlg(s), extra="return __tnTest.stats().routes")
s.js(CLEAN)
R.save()
